// Flag images from flagcdn.com (free, no API key needed)
const FLAG_BASE = "https://flagcdn.com/w40";

export const PRODUCTS = [
  {
    name: "Banana",
    category: "Fruits",
    origin: ["India", "Ecuador", "Philippines"],
    availability: "Year-round",
    emoji: "🍌",
    img: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Apple",
    category: "Fruits",
    origin: ["USA", "Poland", "Italy"],
    availability: "Year-round",
    emoji: "🍎",
    img: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Orange",
    category: "Fruits",
    origin: ["Egypt", "South Africa"],
    availability: "Seasonal",
    emoji: "🍊",
    img: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Mandarin",
    category: "Fruits",
    origin: ["Spain", "Egypt"],
    availability: "Seasonal",
    emoji: "🍊",
    img: "https://images.unsplash.com/photo-1547514701-42782101795e?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Lemon",
    category: "Fruits",
    origin: ["Turkey", "Egypt"],
    availability: "Year-round",
    emoji: "🍋",
    img: "https://images.unsplash.com/photo-1590502593747-42a996133562?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Grapes",
    category: "Fruits",
    origin: ["India", "South Africa"],
    availability: "Seasonal",
    emoji: "🍇",
    img: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Mango",
    category: "Fruits",
    origin: ["India", "Pakistan"],
    availability: "Seasonal",
    emoji: "🥭",
    img: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Pomegranate",
    category: "Fruits",
    origin: ["Turkey", "India"],
    availability: "Seasonal",
    emoji: "🍎",
    img: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Pineapple",
    category: "Fruits",
    origin: ["Philippines"],
    availability: "Year-round",
    emoji: "🍍",
    img: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Kiwi",
    category: "Fruits",
    origin: ["Italy", "New Zealand"],
    availability: "Seasonal",
    emoji: "🥝",
    img: "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Avocado",
    category: "Fruits",
    origin: ["Kenya", "Peru"],
    availability: "Year-round",
    emoji: "🥑",
    img: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Watermelon",
    category: "Fruits",
    origin: ["Egypt", "Iran"],
    availability: "Seasonal",
    emoji: "🍉",
    img: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Melon",
    category: "Fruits",
    origin: ["Spain", "Iran"],
    availability: "Seasonal",
    emoji: "🍈",
    img: "https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Pear",
    category: "Fruits",
    origin: ["Italy", "China"],
    availability: "Seasonal",
    emoji: "🍐",
    img: "https://images.unsplash.com/photo-1665854818426-6197b7e80749?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Strawberry",
    category: "Fruits",
    origin: ["Egypt", "Spain"],
    availability: "Seasonal",
    emoji: "🍓",
    img: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Onion",
    category: "Vegetables",
    origin: ["India", "Netherlands"],
    availability: "Year-round",
    emoji: "🧅",
    img: "https://images.unsplash.com/photo-1508747703725-719777637510?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Potato",
    category: "Vegetables",
    origin: ["India", "Pakistan"],
    availability: "Year-round",
    emoji: "🥔",
    img: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Tomato",
    category: "Vegetables",
    origin: ["Turkey", "Spain"],
    availability: "Year-round",
    emoji: "🍅",
    img: "https://images.unsplash.com/photo-1524593166156-312f362cada0?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Garlic",
    category: "Vegetables",
    origin: ["China", "India"],
    availability: "Year-round",
    emoji: "🧄",
    img: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Ginger",
    category: "Vegetables",
    origin: ["China", "India"],
    availability: "Year-round",
    emoji: "🫚",
    img: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Carrot",
    category: "Vegetables",
    origin: ["Netherlands", "China"],
    availability: "Year-round",
    emoji: "🥕",
    img: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Cabbage",
    category: "Vegetables",
    origin: ["India", "China"],
    availability: "Year-round",
    emoji: "🥬",
    img: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Lettuce",
    category: "Vegetables",
    origin: ["Netherlands", "Spain"],
    availability: "Year-round",
    emoji: "🥬",
    img: "https://images.unsplash.com/photo-1622205313162-be1d5712a43f?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Capsicum",
    category: "Vegetables",
    origin: ["Spain", "Turkey"],
    availability: "Year-round",
    emoji: "🫑",
    img: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Cucumber",
    category: "Vegetables",
    origin: ["India", "Turkey"],
    availability: "Year-round",
    emoji: "🥒",
    img: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Cauliflower",
    category: "Vegetables",
    origin: ["India"],
    availability: "Seasonal",
    emoji: "🥦",
    img: "https://images.unsplash.com/photo-1566842600175-97dca489844f?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Broccoli",
    category: "Vegetables",
    origin: ["Spain", "Italy"],
    availability: "Year-round",
    emoji: "🥦",
    img: "https://plus.unsplash.com/premium_photo-1702403157830-9df749dc6c1e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Eggplant",
    category: "Vegetables",
    origin: ["India", "Turkey"],
    availability: "Year-round",
    emoji: "🍆",
    img: "https://media.istockphoto.com/id/1309479975/photo/ripe-eggplants-growing-in-the-vegetable-garden.jpg?s=1024x1024&w=is&k=20&c=5fdQiwBcgZyEJhN1z70yCJzu-j1XG0Y9Tg2NKpItAXY=",
  },
  {
    name: "Green Chili",
    category: "Vegetables",
    origin: ["India", "Pakistan"],
    availability: "Year-round",
    emoji: "🌶️",
    img: "https://images.unsplash.com/photo-1546860255-95536c19724e?q=80&w=2016&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Okra",
    category: "Vegetables",
    origin: ["India", "Egypt"],
    availability: "Seasonal",
    emoji: "🌿",
    img: "https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

// Country code map for flagcdn.com
export const COUNTRY_CODES = {
  "India": "in",
  "Egypt": "eg",
  "Turkey": "tr",
  "China": "cn",
  "South Africa": "za",
  "Pakistan": "pk",
  "Netherlands": "nl",
  "Italy": "it",
  "Spain": "es",
  "Poland": "pl",
  "UAE": "ae",
  "United Arab Emirates": "ae",
  "Saudi Arabia": "sa",
  "Oman": "om",
  "Qatar": "qa",
  "Bahrain": "bh",
  "Kuwait": "kw",
  "Kenya": "ke",
  "Peru": "pe",
  "Iran": "ir",
  "New Zealand": "nz",
  "Philippines": "ph",
  "Ecuador": "ec",
  "USA": "us",
};

export function getFlagUrl(countryName, size = 40) {
  const code = COUNTRY_CODES[countryName];
  if (!code) return null;
  return `https://flagcdn.com/w${size}/${code}.png`;
}

export const IMPORT_COUNTRIES = [
  { name: "India", flagCode: "in", flag: "🇮🇳", products: "Mango, Onion, Banana, Grapes" },
  { name: "Egypt", flagCode: "eg", flag: "🇪🇬", products: "Orange, Strawberry, Watermelon" },
  { name: "Turkey", flagCode: "tr", flag: "🇹🇷", products: "Lemon, Pomegranate, Tomato" },
  { name: "China", flagCode: "cn", flag: "🇨🇳", products: "Garlic, Ginger, Pear" },
  { name: "South Africa", flagCode: "za", flag: "🇿🇦", products: "Orange, Grapes" },
  { name: "Pakistan", flagCode: "pk", flag: "🇵🇰", products: "Mango, Potato, Chili" },
  { name: "Netherlands", flagCode: "nl", flag: "🇳🇱", products: "Onion, Carrot, Lettuce" },
  { name: "Italy", flagCode: "it", flag: "🇮🇹", products: "Apple, Kiwi, Broccoli" },
  { name: "Spain", flagCode: "es", flag: "🇪🇸", products: "Mandarin, Melon, Capsicum" },
  { name: "Poland", flagCode: "pl", flag: "🇵🇱", products: "Apple" },
];

export const EXPORT_MARKETS = [
  { name: "United Arab Emirates", flagCode: "ae", flag: "🇦🇪", region: "GCC" },
  { name: "Saudi Arabia", flagCode: "sa", flag: "🇸🇦", region: "GCC" },
  { name: "Oman", flagCode: "om", flag: "🇴🇲", region: "GCC" },
  { name: "Qatar", flagCode: "qa", flag: "🇶🇦", region: "GCC" },
  { name: "Bahrain", flagCode: "bh", flag: "🇧🇭", region: "GCC" },
  { name: "Kuwait", flagCode: "kw", flag: "🇰🇼", region: "GCC" },
  { name: "Africa", flagCode: null, flag: "🌍", region: "Continental" },
  { name: "Europe", flagCode: "eu", flag: "🇪🇺", region: "Continental" },
  { name: "South Asia", flagCode: null, flag: "🌏", region: "Continental" },
];

export const SERVICES = [
  { title: "Import Services", desc: "Reliable sourcing and import operations from 15+ origin countries.", icon: "Ship" },
  { title: "Export Services", desc: "Door-to-port export across the GCC, Africa, Europe and South Asia.", icon: "Plane" },
  { title: "Wholesale Supply", desc: "Bulk supply for supermarkets, hotels, restaurants and retail chains.", icon: "Warehouse" },
  { title: "Cold Chain Logistics", desc: "Temperature-controlled storage and reefer transport end-to-end.", icon: "Snowflake" },
  { title: "Documentation Support", desc: "Complete trade documentation, COO, phytosanitary and invoicing.", icon: "FileText" },
  { title: "Customs Clearance", desc: "Expedited UAE customs and re-export clearance services.", icon: "ShieldCheck" },
  { title: "Product Sourcing", desc: "Bespoke sourcing for specialty produce, varieties and grades.", icon: "Search" },
  { title: "Packaging Solutions", desc: "Custom packaging, private label and branded carton printing.", icon: "Package" },
];

export const QUALITY_STEPS = [
  { title: "Supplier Selection", desc: "Audited and pre-qualified grower partnerships across origin countries." },
  { title: "Product Inspection", desc: "On-site inspection at source for grade, size, color and firmness." },
  { title: "Quality Testing", desc: "Lab testing for pesticide residues, ripeness and food safety." },
  { title: "Packaging Verification", desc: "Verified packaging integrity, labeling and traceability codes." },
  { title: "Logistics Monitoring", desc: "Real-time temperature and humidity tracking during transit." },
  { title: "Final Delivery", desc: "Last-mile verification with consignee acceptance and feedback." },
];

export const CERTIFICATIONS = ["HACCP", "ISO 22000", "Food Safety Standards", "GlobalG.A.P.", "Halal"];

export const GALLERY = [
  { tag: "Fresh Produce", emoji: "🍓", grad: "from-rose-500/30 to-orange-500/30", img: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&auto=format&fit=crop" },
  { tag: "Warehouses", emoji: "🏭", grad: "from-slate-500/30 to-emerald-500/30", img: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&auto=format&fit=crop" },
  { tag: "Packaging", emoji: "📦", grad: "from-amber-500/30 to-emerald-500/30", img: "https://images.unsplash.com/photo-1607349913338-fca6f7fc42d0?w=600&auto=format&fit=crop" },
  { tag: "Shipping", emoji: "🚢", grad: "from-blue-500/30 to-cyan-500/30", img: "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=600&auto=format&fit=crop" },
  { tag: "Cold Storage", emoji: "❄️", grad: "from-cyan-500/30 to-blue-500/30", img: "https://tse1.mm.bing.net/th/id/OIP.li3WgE2dBDwv34h-f5019wHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3" },
  { tag: "Inspection", emoji: "🔍", grad: "from-emerald-500/30 to-lime-500/30", img: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop" },
  { tag: "Tropical Fruits", emoji: "🥭", grad: "from-orange-500/30 to-yellow-500/30", img: "https://th.bing.com/th/id/OIP._SFYiNhil2S3ks80SobIBwHaE7?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3" },
  { tag: "Vegetables", emoji: "🥬", grad: "from-emerald-500/30 to-green-500/30", img: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop" },
  { tag: "Logistics Hub", emoji: "🛬", grad: "from-indigo-500/30 to-emerald-500/30", img: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop" },
];